stages:
  evaluate_model:
    cmd: python src/models/evaluate_model.py
    deps:
    - models/landcover_classifier.pkl
    - data/training/X_test.pkl
    - data/training/y_test.pkl
    metrics:
    - metrics/evaluation_metrics.json
    plots:
    - plots/classification_report.png
    - plots/roc_curves.png
  prepare_data:
    cmd: python src/data/prepare_training_data.py
    deps:
    - data/processed/
    - configs/training_config.yaml
    outs:
    - data/training/X_train.pkl
    - data/training/y_train.pkl
    - data/training/X_test.pkl
    - data/training/y_test.pkl
  train_model:
    cmd: python src/models/train_classifier.py
    deps:
    - data/training/
    - configs/training_config.yaml
    metrics:
    - metrics/training_metrics.json
    outs:
    - models/landcover_classifier.pkl
    plots:
    - plots/confusion_matrix.png
    - plots/feature_importance.png
