name: nasa-landcover-unet
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults

dependencies:
  # Python environment
  - python=3.10
  - pip

  # Core scientific computing
  - numpy>=1.24
  - pandas>=2.0
  - scipy>=1.10
  - matplotlib>=3.7
  - seaborn>=0.12
  - plotly>=5.0
  - jupyter
  - jupyterlab
  - ipykernel

  # Deep Learning (PyTorch)
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - pytorch-cuda=11.8  # Adjust based on your CUDA version
  - cudatoolkit=11.8   # CUDA toolkit

  # Geospatial and remote sensing
  - gdal>=3.6
  - rasterio>=1.3
  - xarray>=2023.1
  - netcdf4
  - cartopy
  - geopandas
  - shapely
  - fiona
  - pyproj

  # Machine learning
  - scikit-learn>=1.3
  - xgboost>=1.7
  - lightgbm

  # Deep learning - PyTorch ecosystem
  - pytorch>=2.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # For CUDA support, remove if CPU-only

  # MLflow and experiment tracking
  - mlflow>=2.7
  - mlflow-skinny

  # Data versioning and pipeline
  - dvc[s3]>=3.0

  # Database connectivity
  - sqlalchemy>=2.0
  - psycopg2

  # Web and API
  - requests>=2.28
  - fastapi>=0.100
  - uvicorn[standard]>=0.23

  # Configuration and utilities
  - pyyaml>=6.0
  - python-dotenv>=1.0
  - tqdm>=4.64
  - click>=8.0
  - rich  # For beautiful console output

  # Image processing
  - pillow>=9.0
  - opencv
  - imageio

  # Testing
  - pytest>=7.0
  - pytest-cov
  - pytest-mock

  # Code quality
  - black
  - flake8
  - mypy
  - pre-commit

  # Development utilities
  - ipdb  # Enhanced debugger
  - memory_profiler  # Memory profiling
  - line_profiler  # Line-by-line profiling

  # Additional ML utilities via pip
  - pip:
    # U-Net + SK-ResNeXt50 specific packages
    - timm>=0.9.0  # PyTorch Image Models (SK-ResNeXt50 encoder)
    - segmentation-models-pytorch>=0.3.3  # U-Net implementation
    - torchmetrics>=1.0.0  # Advanced metrics (IoU, etc.)
    - torch-summary  # Model summary for PyTorch

    # Enhanced training utilities
    - albumentations>=1.3.0  # Advanced image augmentations
    - wandb>=0.15.0  # Alternative experiment tracking
    - optuna>=3.0.0  # Hyperparameter optimization

    # Notification libraries
    - slack-sdk>=3.0.0  # Slack notifications
    - twilio>=8.0.0  # SMS notifications (optional)

    # Advanced visualization
    - plotly-dash>=2.0.0  # Interactive dashboards
    - streamlit>=1.25.0  # Web apps for ML

    # Performance monitoring
    - psutil>=5.9.0  # System monitoring
    - py-spy>=0.3.0  # Python profiler

    # Additional utilities
    - python-box>=7.0.0  # Enhanced dictionaries
    - omegaconf>=2.3.0  # Configuration management
    - hydra-core>=1.3.0  # Complex configuration

    # NASA/Earth science specific
    - earthpy>=0.9.0  # Earth data science utilities
    - rioxarray>=0.15.0  # Rasterio + xarray integration
